-- 종목 마스터 — frontend/data/universe.csv 에서 옮겨 온 173종목.
-- 원본: scripts/build_universe.py 가 2026-09-11 기준으로 받은 유니버스.
--
-- 채운 칸: ticker · name · sector · group_id · risk_tag
-- 비워 둔 칸과 이유:
--   volatility_1y  원본 값이 3년 변동성이라 칸 이름(1년)과 기간이 다르다.
--                  그대로 넣으면 나중에 1년치로 오해한다.
--   listed_date    원본의 first_date 는 시세 수집 시작일이지 상장일이 아니다.
--   mdd_3y · expense_ratio · delisted_date   원본에 없다.
--
-- ⚠ risk_tag 는 3년 일간 변동성으로 자동 산정한 값이고 금융투자협회 공시 등급이 아니다.
--   173종목 중 87개가 G1(초고위험)으로 잡혀 있고, KODEX 200 같은 국내 대표지수도 G1 이다.
--   이대로 두면 안정투자형이 담을 수 있는 주식형이 14종목뿐이다.
--   TODO: 사람이 검토해서 재배정할 것 (자동 추정 금지 규칙 대상 칸이다).
--
-- 이 파일에 없는 것: 레버리지·인버스 종목과 상장폐지 종목.
--   원본 수집 단계에서 걸러졌다. 데모의 '생성 불가' / '상장폐지 차단' 장면에는 따로 넣어야 한다.

INSERT INTO etf_master (ticker, name, sector, group_id, risk_tag, is_leveraged, active)
VALUES
    ('069500', 'KODEX 200', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('360750', 'TIGER 미국S&P500', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('133690', 'TIGER 미국나스닥100', 'SECTOR_OTHER', 'EQUITY', 'G2', false, true),
    ('102110', 'TIGER 200', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('379800', 'KODEX 미국S&P500', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('396500', 'TIGER 반도체TOP10', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('379810', 'KODEX 미국나스닥100', 'SECTOR_OTHER', 'EQUITY', 'G2', false, true),
    ('278530', 'KODEX 200TR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('459580', 'KODEX CD금리액티브(합성)', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('091160', 'KODEX 반도체', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('381180', 'TIGER 미국필라델피아반도체나스닥', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('229200', 'KODEX 코스닥150', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('310970', 'TIGER MSCI Korea TR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('148020', 'RISE 200', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('458730', 'TIGER 미국배당다우존스', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('395160', 'KODEX AI반도체TOP2플러스', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('411060', 'ACE KRX금현물', 'SECTOR_OTHER', 'COMMODITY', 'G1', false, true),
    ('360200', 'ACE 미국S&P500', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('381170', 'TIGER 미국테크TOP10 INDXX', 'SECTOR_INTERNET_PLATFORM', 'EQUITY', 'G2', false, true),
    ('423160', 'KODEX KOFR금리액티브(합성)', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('395270', 'HANARO Fn K-반도체', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('357870', 'TIGER CD금리투자KIS(합성)', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('273130', 'KODEX 종합채권(AA-이상)액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('367380', 'ACE 미국나스닥100', 'SECTOR_OTHER', 'EQUITY', 'G2', false, true),
    ('102780', 'KODEX 삼성그룹', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('455890', 'RISE 머니마켓액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('139260', 'TIGER 200 IT', 'SECTOR_INTERNET_PLATFORM', 'EQUITY', 'G1', false, true),
    ('161510', 'PLUS 고배당주', 'SECTOR_OTHER', 'EQUITY', 'G2', false, true),
    ('426030', 'TIME 미국나스닥100액티브', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('449170', 'TIGER KOFR금리액티브(합성)', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('278540', 'KODEX MSCI Korea TR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('385540', 'RISE 종합채권(A-이상)액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('456600', 'TIME 글로벌AI인공지능액티브', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('284430', 'KODEX 200미국채혼합50', 'SECTOR_OTHER', 'BOND', 'G3', false, true),
    ('292150', 'TIGER 코리아TOP10', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('294400', 'KIWOOM 200TR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('214980', 'KODEX 단기채권PLUS', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('305720', 'KODEX 2차전지산업', 'SECTOR_BATTERY', 'EQUITY', 'G1', false, true),
    ('442580', 'PLUS 글로벌HBM반도체', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('105190', 'ACE 200', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('441640', 'KODEX 미국배당커버드콜액티브', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('329200', 'TIGER 리츠부동산인프라', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('446770', 'ACE 글로벌반도체TOP4 Plus', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('368590', 'RISE 미국나스닥100', 'SECTOR_OTHER', 'EQUITY', 'G2', false, true),
    ('152100', 'PLUS 200', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('453850', 'ACE 미국30년국채액티브(H)', 'SECTOR_OTHER', 'BOND', 'G4', false, true),
    ('379780', 'RISE 미국S&P500', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('226490', 'KODEX 코스피', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('091230', 'TIGER 반도체', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('232080', 'TIGER 코스닥150', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('157450', 'TIGER 단기통안채', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('448330', 'KODEX 삼성전자채권혼합', 'SECTOR_OTHER', 'BOND', 'G3', false, true),
    ('436140', 'SOL 종합채권(AA-이상)액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('390390', 'KODEX 미국반도체', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('438080', 'ACE 미국S&P500미국채혼합50액티브', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('356540', 'ACE 종합채권(AA-이상)액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('445290', 'KODEX 로봇액티브', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('465580', 'ACE 미국빅테크TOP7 Plus', 'SECTOR_INTERNET_PLATFORM', 'EQUITY', 'G1', false, true),
    ('455850', 'SOL AI반도체소부장', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('451540', 'TIGER 종합채권(AA-이상)액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('449180', 'KODEX 미국S&P500(H)', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('295040', 'SOL 200TR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('446720', 'SOL 미국배당다우존스', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('449450', 'PLUS K방산', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('315930', 'KODEX Top5PlusTR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('237350', 'KODEX 코스피100', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('305540', 'TIGER 2차전지테마', 'SECTOR_BATTERY', 'EQUITY', 'G1', false, true),
    ('402970', 'ACE 미국배당다우존스', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('438100', 'ACE 미국나스닥100미국채혼합50액티브', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('153130', 'KODEX 단기채권', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('441800', 'TIME Korea플러스배당액티브', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('069660', 'KIWOOM 200', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('272580', 'TIGER 단기채권액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('144600', 'KODEX 은선물(H)', 'SECTOR_OTHER', 'COMMODITY', 'G1', false, true),
    ('457480', 'ACE 테슬라밸류체인액티브', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('434730', 'HANARO 원자력iSelect', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('364980', 'TIGER 2차전지TOP10', 'SECTOR_BATTERY', 'EQUITY', 'G1', false, true),
    ('456610', 'TIGER 미국달러SOFR금리액티브(합성)', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('102970', 'KODEX 증권', 'SECTOR_FINANCE', 'EQUITY', 'G1', false, true),
    ('458760', 'TIGER 미국배당다우존스타겟커버드콜2호', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('290130', 'RISE ESG사회책임투자', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('329750', 'TIGER 미국달러단기채권액티브', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('367760', 'RISE 네트워크인프라', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('138540', 'TIGER 현대차그룹플러스', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('371460', 'TIGER 차이나전기차SOLACTIVE', 'SECTOR_BATTERY', 'EQUITY', 'G1', false, true),
    ('314250', 'KODEX 미국빅테크10(H)', 'SECTOR_INTERNET_PLATFORM', 'EQUITY', 'G1', false, true),
    ('434060', 'KODEX TDF2050액티브 적격', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('277630', 'TIGER 코스피', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('251600', 'PLUS 고배당주채권혼합', 'SECTOR_OTHER', 'BOND', 'G4', false, true),
    ('449190', 'KODEX 미국나스닥100(H)', 'SECTOR_OTHER', 'EQUITY', 'G2', false, true),
    ('462010', 'TIGER 2차전지소재Fn', 'SECTOR_BATTERY', 'EQUITY', 'G1', false, true),
    ('451000', 'PLUS 종합채권(AA-이상)액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('455030', 'KODEX 미국달러SOFR금리액티브(합성)', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('438330', 'TIGER 우량회사채액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('371160', 'TIGER 차이나항셍테크', 'SECTOR_INTERNET_PLATFORM', 'EQUITY', 'G1', false, true),
    ('315960', 'RISE 대형고배당10TR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('396520', 'TIGER 차이나반도체FACTSET', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('365780', 'ACE 국고채10년', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('444200', 'SOL 코리아메가테크액티브', 'SECTOR_INTERNET_PLATFORM', 'EQUITY', 'G1', false, true),
    ('463250', 'TIGER K방산&우주', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('361580', 'RISE 200TR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('435420', 'TIGER 미국나스닥100채권혼합50', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('114260', 'KODEX 국고채3년', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('251350', 'KODEX MSCI선진국', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('385560', 'RISE KIS국고채30년Enhanced', 'SECTOR_OTHER', 'BOND', 'G4', false, true),
    ('448290', 'TIGER 미국S&P500(H)', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('451060', '1Q 200액티브', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('447770', 'TIGER 테슬라채권혼합Fn', 'SECTOR_OTHER', 'BOND', 'G2', false, true),
    ('293180', 'HANARO 200', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('148070', 'KIWOOM 국고채10년', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('448300', 'TIGER 미국나스닥100(H)', 'SECTOR_OTHER', 'EQUITY', 'G2', false, true),
    ('302450', 'RISE 코스피', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('385720', 'TIME 코스피액티브', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('426020', 'TIME 미국S&P500액티브', 'SECTOR_OTHER', 'EQUITY', 'G2', false, true),
    ('091180', 'KODEX 자동차', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('241180', 'TIGER 일본니케이225', 'SECTOR_OTHER', 'EQUITY', 'G2', false, true),
    ('385550', 'RISE 단기채권알파액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('458250', 'TIGER 미국30년국채스트립액티브(합성 H)', 'SECTOR_OTHER', 'BOND', 'G2', false, true),
    ('439860', 'KODEX ESG종합채권(A-이상)액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('132030', 'KODEX 골드선물(H)', 'SECTOR_OTHER', 'COMMODITY', 'G2', false, true),
    ('310960', 'TIGER 200TR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('279530', 'KODEX 고배당주', 'SECTOR_OTHER', 'EQUITY', 'G2', false, true),
    ('462900', 'KoAct 바이오헬스케어액티브', 'SECTOR_BIOHEALTH', 'EQUITY', 'G1', false, true),
    ('442570', 'RISE TDF2050액티브 적격', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('385510', 'KODEX 신재생에너지액티브', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('190620', 'ACE 단기통안채', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('456880', 'ACE 미국달러SOFR금리(합성)', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('448630', 'RISE 삼성그룹Top3채권혼합', 'SECTOR_OTHER', 'BOND', 'G4', false, true),
    ('453810', 'KODEX 인도Nifty50', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('270810', 'RISE 코스닥150', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('091170', 'KODEX 은행', 'SECTOR_FINANCE', 'EQUITY', 'G1', false, true),
    ('439870', 'KODEX 국고채30년액티브', 'SECTOR_OTHER', 'BOND', 'G4', false, true),
    ('433330', 'SOL 미국S&P500', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('136340', 'RISE 중기우량회사채', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('454780', 'KIWOOM 종합채권(AA-이상)액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('307520', 'TIGER 지주회사', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('273140', 'KODEX 단기변동금리부채권액티브', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('461490', 'RISE 글로벌자산배분액티브', 'SECTOR_OTHER', 'EQUITY', 'G5', false, true),
    ('441680', 'TIGER 미국나스닥100커버드콜(합성)', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('453870', 'TIGER 인도니프티50', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('213610', 'KODEX 삼성그룹밸류', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('196230', 'RISE 단기통안채', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('245710', 'ACE 베트남VN30(합성)', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('139230', 'TIGER 200 중공업', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('228790', 'TIGER 화장품', 'SECTOR_CONSUMER', 'EQUITY', 'G1', false, true),
    ('423170', 'SOL 글로벌AI반도체탑픽액티브', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('364970', 'TIGER 바이오TOP10', 'SECTOR_BIOHEALTH', 'EQUITY', 'G1', false, true),
    ('421320', 'PLUS 우주항공', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('283580', 'KODEX 차이나CSI300', 'SECTOR_OTHER', 'EQUITY', 'G3', false, true),
    ('448540', 'ACE 엔비디아채권혼합', 'SECTOR_OTHER', 'BOND', 'G3', false, true),
    ('117700', 'KODEX 건설', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('388420', 'RISE 비메모리반도체액티브', 'SECTOR_SEMICONDUCTOR', 'EQUITY', 'G1', false, true),
    ('363580', 'KODEX 200IT TR', 'SECTOR_INTERNET_PLATFORM', 'EQUITY', 'G1', false, true),
    ('433500', 'ACE 원자력TOP10', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('363570', 'KODEX 장기종합채권(AA-이상)액티브', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('452360', 'SOL 미국배당다우존스(H)', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('329650', 'KODEX TRF3070', 'SECTOR_OTHER', 'EQUITY', 'G6', false, true),
    ('442320', 'RISE 글로벌원자력', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('437080', 'KODEX 미국종합채권ESG액티브(H)', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('422420', 'RISE 2차전지액티브', 'SECTOR_BATTERY', 'EQUITY', 'G1', false, true),
    ('157500', 'TIGER 증권', 'SECTOR_FINANCE', 'EQUITY', 'G1', false, true),
    ('458260', 'TIGER 미국투자등급회사채액티브(H)', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('266160', 'RISE 고배당', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('305080', 'TIGER 미국채10년선물', 'SECTOR_OTHER', 'BOND', 'G5', false, true),
    ('332930', 'HANARO 200TR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('244580', 'KODEX 바이오', 'SECTOR_BIOHEALTH', 'EQUITY', 'G1', false, true),
    ('463050', 'TIME K바이오액티브', 'SECTOR_BIOHEALTH', 'EQUITY', 'G1', false, true),
    ('302190', 'TIGER 중장기국채', 'SECTOR_OTHER', 'BOND', 'G6', false, true),
    ('433980', 'KODEX TDF2040액티브 적격', 'SECTOR_OTHER', 'EQUITY', 'G5', false, true),
    ('429000', 'TIGER 미국S&P500배당귀족', 'SECTOR_OTHER', 'EQUITY', 'G4', false, true),
    ('461950', 'KODEX 2차전지핵심소재10', 'SECTOR_BATTERY', 'EQUITY', 'G1', false, true),
    ('122090', 'PLUS 코스피50', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true),
    ('332500', 'ACE 200TR', 'SECTOR_OTHER', 'EQUITY', 'G1', false, true)
ON CONFLICT (ticker) DO NOTHING;
